# Generated by Django 5.1.6 on 2025-05-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=10)),
                ('Married', models.CharField(max_length=10)),
                ('Dependents', models.CharField(max_length=10)),
                ('Education', models.CharField(max_length=20)),
                ('Self_Employed', models.CharField(max_length=10)),
                ('LoanAmount', models.FloatField()),
                ('Loan_Amount_Term', models.FloatField()),
                ('Credit_History', models.FloatField()),
                ('Property_Area', models.CharField(max_length=20)),
                ('TotalIncome', models.FloatField()),
                ('Prediction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
